require:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - db/**/*
    - bin/**/*
    - config/initializers/themes/*

Style:
  Enabled: false

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes
